"use client";
import { useState, useRef } from "react";
import { 
  FiFileText, FiUploadCloud, FiCheckCircle, FiClock, FiAlertCircle, 
  FiDownload, FiTrash2, FiX, FiPaperclip, FiAward 
} from "react-icons/fi";

// --- ADVANCED MOCK DATA ---
const INITIAL_ASSIGNMENTS = [
  { 
    id: 1, 
    title: "React Hooks Implementation", 
    course: "Advanced React Patterns", 
    marks: 100, 
    dueDate: "Tomorrow, 11:59 PM", 
    status: "Pending", 
    description: "Build a custom hook that fetches data and handles loading/error states.",
    attachment: "project_requirements.pdf"
  },
  { 
    id: 2, 
    title: "UI Design System", 
    course: "UI/UX Masterclass", 
    marks: 50, 
    dueDate: "Yesterday", 
    status: "Late", 
    description: "Create a style guide for the dashboard project.",
    attachment: null
  },
  { 
    id: 3, 
    title: "Backend API Integration", 
    course: "Node.js Architecture", 
    marks: 100, 
    dueDate: "2 days ago", 
    status: "Submitted", 
    submittedDate: "Oct 24, 5:30 PM",
    submittedFile: "api_v1_final.zip",
    description: "Connect the frontend to the Express API endpoints."
  },
  { 
    id: 4, 
    title: "Data Structures Quiz", 
    course: "Computer Science 101", 
    marks: 20, 
    dueDate: "Last Week", 
    status: "Graded", 
    grade: 18,
    feedback: "Excellent work on the binary trees section! Keep it up.",
    submittedDate: "Oct 20, 10:00 AM",
    submittedFile: "quiz_answers.pdf"
  }
];

export default function StudentAssignments() {
  const [tasks, setTasks] = useState(INITIAL_ASSIGNMENTS);
  const [filter, setFilter] = useState("All");
  
  // Upload States
  const [uploadingId, setUploadingId] = useState(null);
  const [selectedFiles, setSelectedFiles] = useState({}); 
  const [dragActiveId, setDragActiveId] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null); // For loading state
  const fileInputRefs = useRef({});

  // Filter Logic
  const filteredTasks = tasks.filter(t => {
    if (filter === "All") return true;
    if (filter === "Pending") return t.status === "Pending" || t.status === "Late";
    return t.status === filter;
  });

  // --- DOWNLOAD GRADED FILE LOGIC (NEW) ---
  const handleDownloadGradedFile = (task) => {
    setDownloadingId(task.id);

    // Simulate Network Delay
    setTimeout(() => {
        // Create a dummy content for the file
        const fileContent = `
COURSE: ${task.course}
ASSIGNMENT: ${task.title}
------------------------------------------------
STUDENT: Arjun Mehta
GRADE: ${task.grade} / ${task.marks}
STATUS: Graded
------------------------------------------------
TEACHER FEEDBACK:
"${task.feedback}"

------------------------------------------------
(This is a verified checked copy generated by EduNexus)
        `;

        // Create a Blob
        const blob = new Blob([fileContent], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        
        // Trigger Download
        const a = document.createElement("a");
        a.href = url;
        a.download = `Graded_${task.title.replace(/\s+/g, "_")}.txt`;
        document.body.appendChild(a);
        a.click();
        
        // Cleanup
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setDownloadingId(null);
    }, 1500);
  };

  // --- FILE HANDLING LOGIC ---
  const handleFileSelect = (taskId, e) => {
    const file = e.target.files[0];
    if (file) setSelectedFiles(prev => ({ ...prev, [taskId]: file }));
  };

  const handleDrag = (e, taskId) => {
    e.preventDefault(); e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActiveId(taskId);
    else if (e.type === "dragleave") setDragActiveId(null);
  };

  const handleDrop = (e, taskId) => {
    e.preventDefault(); e.stopPropagation();
    setDragActiveId(null);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
       setSelectedFiles(prev => ({ ...prev, [taskId]: e.dataTransfer.files[0] }));
    }
  };

  const removeSelectedFile = (taskId) => {
    const newFiles = { ...selectedFiles };
    delete newFiles[taskId];
    setSelectedFiles(newFiles);
    if(fileInputRefs.current[taskId]) fileInputRefs.current[taskId].value = "";
  };

  // --- SUBMISSION SIMULATION ---
  const handleSubmit = (taskId) => {
    const file = selectedFiles[taskId];
    if (!file) return;

    setUploadingId(taskId);
    setTimeout(() => {
      setTasks(prev => prev.map(t => 
        t.id === taskId ? { ...t, status: "Submitted", submittedDate: "Just Now", submittedFile: file.name } : t
      ));
      setUploadingId(null);
      removeSelectedFile(taskId);
    }, 2000);
  };

  return (
    <div className="space-y-8 font-sans text-slate-900 pb-20">
      
      {/* --- HEADER --- */}
      <div className="flex flex-col md:flex-row justify-between items-end gap-4 animate-in slide-in-from-top-4 duration-500">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight">Assignments & Homework</h1>
          <p className="text-slate-500 mt-2 flex items-center gap-2">
             <FiClock className="text-indigo-500"/> 
             You have {tasks.filter(t => t.status === 'Pending' || t.status === 'Late').length} pending assignments.
          </p>
        </div>
        
        <div className="bg-white p-1.5 rounded-xl border border-slate-200 shadow-sm flex overflow-x-auto no-scrollbar">
          {["All", "Pending", "Submitted", "Graded"].map(tab => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`px-5 py-2 rounded-lg text-sm font-bold transition-all whitespace-nowrap ${
                filter === tab ? "bg-slate-900 text-white shadow-md" : "text-slate-500 hover:bg-slate-50 hover:text-slate-700"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>

      {/* --- ASSIGNMENT LIST --- */}
      <div className="space-y-6">
        {filteredTasks.map((task) => (
          <div key={task.id} className={`bg-white border rounded-2xl p-6 transition-all duration-300 hover:shadow-lg flex flex-col lg:flex-row gap-8 ${
             task.status === 'Late' ? 'border-red-200 bg-red-50/10' : 'border-slate-200'
          }`}>
            
            {/* LEFT: Info */}
            <div className="flex-1 flex gap-5">
              <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-2xl shrink-0 shadow-sm ${
                task.status === 'Pending' ? 'bg-orange-100 text-orange-600' :
                task.status === 'Late' ? 'bg-red-100 text-red-600' :
                task.status === 'Graded' ? 'bg-green-100 text-green-600' :
                'bg-blue-100 text-blue-600'
              }`}>
                {task.status === 'Graded' ? <FiAward /> : <FiFileText />}
              </div>
              
              <div className="space-y-2 w-full">
                <div className="flex flex-wrap justify-between items-start gap-2">
                   <div>
                      <h3 className="font-bold text-xl text-slate-900">{task.title}</h3>
                      <p className="text-sm text-slate-500 font-medium">{task.course}</p>
                   </div>
                   <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border ${
                      task.status === 'Pending' ? 'bg-orange-50 text-orange-600 border-orange-200' :
                      task.status === 'Late' ? 'bg-red-50 text-red-600 border-red-200' :
                      task.status === 'Graded' ? 'bg-green-50 text-green-600 border-green-200' :
                      'bg-blue-50 text-blue-600 border-blue-200'
                   }`}>
                      {task.status}
                   </span>
                </div>
                <p className="text-slate-600 text-sm leading-relaxed max-w-2xl">{task.description}</p>
                <div className="flex flex-wrap items-center gap-4 text-xs font-bold text-slate-400 pt-2">
                   <span className={`flex items-center gap-1 ${task.status === 'Late' ? 'text-red-500' : ''}`}>
                      <FiClock /> Due: {task.dueDate}
                   </span>
                   <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
                   <span>Points: {task.marks}</span>
                </div>
              </div>
            </div>

            {/* RIGHT: Actions */}
            <div className="w-full lg:w-80 border-t lg:border-t-0 lg:border-l border-slate-100 pt-6 lg:pt-0 lg:pl-8 flex flex-col justify-center shrink-0">
               
               {/* UPLOAD (Pending/Late) */}
               {(task.status === 'Pending' || task.status === 'Late') && (
                 <div className="space-y-3">
                    {selectedFiles[task.id] ? (
                       <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-3 animate-in zoom-in-95">
                          <div className="flex items-center justify-between mb-2">
                             <div className="flex items-center gap-2 overflow-hidden">
                                <div className="bg-white p-2 rounded-lg text-indigo-600"><FiFileText /></div>
                                <span className="text-xs font-bold text-slate-700 truncate">{selectedFiles[task.id].name}</span>
                             </div>
                             <button onClick={() => removeSelectedFile(task.id)} className="text-slate-400 hover:text-red-500"><FiX /></button>
                          </div>
                          <button onClick={() => handleSubmit(task.id)} disabled={uploadingId === task.id} className="w-full bg-indigo-600 text-white py-2 rounded-lg text-xs font-bold shadow-md hover:bg-indigo-700 disabled:opacity-70 disabled:cursor-wait flex items-center justify-center gap-2 transition-all">
                             {uploadingId === task.id ? <>Uploading...</> : <><FiUploadCloud size={14} /> Submit Assignment</>}
                          </button>
                       </div>
                    ) : (
                       <div 
                          onDragEnter={(e) => handleDrag(e, task.id)} onDragLeave={(e) => handleDrag(e, task.id)} onDragOver={(e) => handleDrag(e, task.id)} onDrop={(e) => handleDrop(e, task.id)} onClick={() => fileInputRefs.current[task.id].click()}
                          className={`border-2 border-dashed rounded-xl p-6 text-center cursor-pointer transition-all duration-200 group ${dragActiveId === task.id ? 'border-indigo-500 bg-indigo-50' : 'border-slate-300 hover:border-indigo-400 hover:bg-slate-50'}`}
                       >
                          <input type="file" className="hidden" ref={el => fileInputRefs.current[task.id] = el} onChange={(e) => handleFileSelect(task.id, e)} />
                          <div className="w-10 h-10 bg-slate-100 text-slate-400 rounded-full flex items-center justify-center mx-auto mb-3 group-hover:bg-indigo-100 group-hover:text-indigo-600 transition-colors"><FiUploadCloud size={20} /></div>
                          <p className="text-xs font-bold text-slate-700">Click or Drag file here</p>
                       </div>
                    )}
                 </div>
               )}

               {/* SUBMITTED */}
               {task.status === 'Submitted' && (
                 <div className="bg-slate-50 rounded-xl p-4 border border-slate-200">
                    <div className="flex items-center gap-2 text-green-600 mb-3"><FiCheckCircle className="fill-green-100" size={20} /><span className="text-sm font-bold">Submitted</span></div>
                    <div className="text-xs text-slate-500 space-y-1 pl-7 border-l-2 border-slate-200">
                       <p>File: <span className="font-medium text-slate-700">{task.submittedFile}</span></p>
                       <p>Date: {task.submittedDate}</p>
                    </div>
                    <button className="w-full mt-4 text-xs font-bold text-slate-500 border border-slate-300 py-2 rounded-lg hover:bg-white hover:text-red-500 transition-colors flex items-center justify-center gap-2"><FiTrash2 /> Undo</button>
                 </div>
               )}

               {/* GRADED (DOWNLOAD WORKING HERE) */}
               {task.status === 'Graded' && (
                 <div className="bg-green-50 rounded-xl p-4 border border-green-100 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-3 opacity-10"><FiAward size={60} className="text-green-800"/></div>
                    <div className="relative z-10">
                       <p className="text-xs font-bold text-green-700 uppercase mb-1">Grade Achieved</p>
                       <div className="flex items-end gap-1 mb-3">
                          <span className="text-3xl font-extrabold text-green-800">{task.grade}</span>
                          <span className="text-sm font-bold text-green-600 mb-1">/ {task.marks}</span>
                       </div>
                       <div className="bg-white/60 p-2 rounded-lg backdrop-blur-sm">
                          <p className="text-[10px] font-bold text-green-800 uppercase mb-0.5">Feedback:</p>
                          <p className="text-xs text-green-900 italic">"{task.feedback}"</p>
                       </div>
                       
                       {/* DOWNLOAD BUTTON (WORKING) */}
                       <button 
                         onClick={() => handleDownloadGradedFile(task)}
                         disabled={downloadingId === task.id}
                         className="w-full mt-3 text-xs font-bold text-green-700 flex items-center justify-center gap-1 hover:underline disabled:opacity-50 disabled:cursor-wait"
                       >
                          {downloadingId === task.id ? (
                              "Downloading..."
                          ) : (
                              <><FiDownload /> Download Graded File</>
                          )}
                       </button>
                    </div>
                 </div>
               )}

            </div>
          </div>
        ))}

        {filteredTasks.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
             <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-4"><FiAlertCircle className="text-slate-300" size={32} /></div>
             <h3 className="text-lg font-bold text-slate-900">No Assignments Found</h3>
             <p className="text-slate-500 text-sm max-w-xs mt-2">There are no assignments in the "{filter}" category.</p>
             <button onClick={() => setFilter('All')} className="mt-4 text-indigo-600 text-sm font-bold hover:underline">View All Assignments</button>
          </div>
        )}
      </div>
    </div>
  );
}